title: Mark Paral
subtitle: Aero Astro Engineer
description: >- # this means to ignore newlines until "baseurl:"

url: "https://markparal.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
#    - text: Shop
#      url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: CircuitRocket.png
author_pic: Headshot.jpg
author: Mark Paral
author_bio: Hello! My name is Mark Paral and I am a Master's student studying Aeronautical and Astronautical Engineering at Stanford University!
author_email: "markwparal@gmail.com"
author_location: USA
author_website_url: "https://markparal.com"
welcome_message: This website is under construction and will be updated soon!
hero_cover_img: cygnus.png # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img
author_skills: Not HTML!

# Experiences
author_work_experiences:
            - company_name: Lynk Global - (May 2023 - Aug 2023)
              company_logo: Lynk.png
              company_url: https://lynk.world/
              designation: Engineering Intern
              description: "Assembled hardware-in-the-loop (HWIL) setup for novel direct-to-phone satellites<br><br>Developed and adapted software for handling CAN network interfaces between sensors, actuators, and dynamics simulator in C<br><br>Built sensor simulators using microcontrollers<br><br>Automated reaction wheel qualification testing"
              visibility: true
            - company_name: Blue Origin - (May 2022 - Aug 2022)
              company_logo: blueorigin.jpg
              company_url: https://www.blueorigin.com/
              designation: Avionics Hardware Intern
              description: "Developed novel solution to enhance and expand sensor infrastructure on the New Shepard Propulsion Module<br><br>Designed custom PCBs for signal conditioning and power distribution on the New Shepard launch vehicle<br><br>Performed audit of New Shepard crew capsule sensors<br><br>Wrote engineering work orders to resolve non-conformance reports"
              visibility: true
            - company_name: Firefly Aerospace - (Jan 2022 - May 2022)
              company_logo: firefly.png
              company_url: https://fireflyspace.com/
              designation: Avionics Intern
              description: "Developed custom hardware and software solution to automate qualification process for harnessing on all vehicles<br><br>Constructed payload wiring diagrams for the Alpha launch vehicle in Siemens Capital software<br><br>Created and led a test campaign to qualify securing devices used on multiple spacecraft<br><br>Built custom Python executables to allow for quick updates to components in Siemens Capital software"
              visibility: true

# Education
author_education_details:
              - college_logo: stanford.jpg
                college_name: Stanford
                college_url: https://www.stanford.edu/
                college_degree: Aero Astro Engineering
                description: Master of Science
                visibility: true
              - college_logo: purdue.jpg
                college_name: Purdue
                college_url: https://www.purdue.edu/
                college_degree: Aero Astro Engineering
                description: Bachelor of Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
#twitter_username: johndoe
github_username:  markparal
#facebook_username: johndoe
linkedin_username: www.linkedin.com/in/mark-paral
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
